package fanlib;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Librostext2Test {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	String[] titulos = { "Título Corto 1", "Título Largo 2 con más palabras",
			"Título Muy Largo 3 con una cantidad significativa de palabras y caracteres", "Título 4", "Título 5",
			"Título 6", null, "Título Largo 8 con más palabras", "Título 9", "Título Corto 10" };

	String[] fechas = { "2024-01-20", "2024-02-15", "2024-03-10", "2024-04-05", "2024-05-25", "2024-06-18",
			"2024-07-30", "2024-08-12", "2024-09-09", "2024-10-03" };

	String[] resenas = { "Reseña corta 1", "Reseña 2 con más palabras y contenido interesante",
			"Reseña 3 con una cantidad significativa de palabras y caracteres para probar límites", "Reseña 4",
			"Reseña 5", null, "Reseña 7", "Reseña 8 con más contenido y detalles", "Reseña 9",
			"Reseña corta 10" };

	String[] generos = { "1", "2", "3", "4", "5", "1", null, "3", "4", "5" }; // Ejemplo de géneros como enteros

	String[] portadas = { "portada1.jpg", "portada2.png", "portada3.jpeg", "portada4.gif", "portada5.bmp",
			"portada6.jpg", "portada7.png", "portada8.jpeg", "portada9.gif", "portada10.bmp" };

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void librostext2() {
		for (int i = 0; i < generos.length; i++) {
			driver.get("https://06.2daw.esvirgua.com/ProyectoMalaga/index.html");
			driver.manage().window().setSize(new Dimension(826, 666));
			driver.findElement(By.id("btnaltalibros")).click();
			driver.findElement(By.id("tituloInput")).click();
			driver.findElement(By.id("tituloInput")).sendKeys(titulos[i]);
			driver.findElement(By.id("fechaPublicacionInput")).click();
			driver.findElement(By.id("fechaPublicacionInput")).sendKeys(fechas[i]);
			driver.findElement(By.id("resenaInput")).click();
			driver.findElement(By.id("resenaInput")).sendKeys(resenas[i]);
			driver.findElement(By.id("generoInput")).click();
			driver.findElement(By.id("generoInput")).sendKeys(generos[i]);
			 try {
					
			    	driver.findElement(By.id("portadaInput")).click();
			    	driver.findElement(By.id("portadaInput")).sendKeys("C:\\fakepath\\" + portadas[i]);
				} catch (Exception e) {
//					InvalidArgumentException
				}
			driver.findElement(By.id("enviarlibro")).click();
		}
	}
}
